import styled from "styled-components";
import Head from "next/head";
import MorePosts from "./MorePosts"

export default function AboutLayout({ meta, children }) {
  return (
    <>
      <Head>
        <title>{`${meta.title} | Marco Pacifico`}</title>
        <meta property="og:title" content={meta.title} key="title" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <h1>{meta.title}</h1>
        <h2>{meta.description}</h2>
        {children}
      </Section>
      <MorePosts currentPost={meta.slug}/>
    </>
  );
}

const Wrapper = styled.div`
  padding: 8rem;
`;
const Section = styled.section`
  max-width: 600px;
  margin: 0 auto;
  min-height: 100vh;
  /* padding: 4rem 0; */
  justify-content: flex-start;
  align-items: flex-start;
`;
