import styled from "styled-components";
import Head from "next/head";

export default function AboutLayout({ meta, children }) {
  return (
    <Wrapper>
      <Head>
        <title>{meta.title} | Marco Pacifico</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{meta.title}</h1>
      <h2>{meta.description}</h2>
      <Main>{children}</Main>
    </Wrapper>
  );
}

const Wrapper = styled.div`
  padding: 0 2rem;
`;
const Main = styled.main`
  max-width: 600px;
  margin: 0 auto;
  min-height: 100vh;
  padding: 4rem 0;
`;
