import styled from "styled-components"
import Head from 'next/head'
import DarkToggle from "./DarkToggle"

export default function Layout({ children }) {
    return (
        <>
        <Wrapper>
            <Head>
                <title>Testing Testing</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <header>
                <DarkToggle/>
            </header>
            <Main>
                {children}
            </Main>
        </Wrapper>
        <Footer></Footer>
        </>
    )
}

const Wrapper = styled.div`
  padding: 0 2rem;
`
const Main = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`
const Footer = styled.footer`
  display: flex;
  flex: 1;
  padding: 2rem 0;
  border-top: 1px solid #eaeaea;
  justify-content: center;
  align-items: center;

  & a {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-grow: 1;
  }

  @media (prefers-color-scheme: dark) {
    border-color: #222;
  }
`