import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'

export default function Home() {
  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Title>
          I changed this title to test live previews.
        </Title>

        <Description>
          Get started by editing{' '}
          <Code>pages/index.tsx</Code>
        </Description>

        <Grid>
          <Card href="https://nextjs.org/docs" >
            <CardTitle>Documentation &rarr;</CardTitle>
            <CardDescription>Millions of companies of all sizes—from startups to Fortune 500s—use Stripe’s software and APIs to accept payments, send payouts, and manage their businesses online.</CardDescription>
          </Card>

          <Card href="https://nextjs.org/learn">
            <CardTitle>Learn &rarr;</CardTitle>
            <CardDescription>Learn about Next.js in an interactive course with quizzes!</CardDescription>
          </Card>

          <Card
            href="https://github.com/vercel/next.js/tree/canary/examples"
          >
            <CardTitle>Examples &rarr;</CardTitle>
            <CardDescription>Discover and deploy boilerplate example Next.js projects.</CardDescription>
          </Card>

          <Card
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <CardTitle>Deploy &rarr;</CardTitle>
            <CardDescription>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </CardDescription>
          </Card>
        </Grid>
      </Main>

      <Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <Logo>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </Logo>
        </a>
      </Footer>
    </Wrapper>
  )
}

const Wrapper = styled.div`
  padding: 0 2rem;
`
const Main = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`

const Title = styled.h1`
  margin: 0;
  line-height: 1.04;
  font-size: 80px;
  letter-spacing: -3.1725px;
  text-align: center;
  font-weight: 500;

  & a {
    color: #0070f3;
    text-decoration: none;

    &:hover, :focus, :active {
      text-decoration: underline;
    }
  }
`
const Description = styled.p`
  margin: 4rem 0;
  line-height: 1.5;
  font-size: 1.5rem;
  text-align: center;
  font-weight: 300;
`
const Code = styled.code`
  background: #fafafa;
  border-radius: 5px;
  padding: 0.75rem;
  font-size: 1.1rem;
  font-family: Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono,
    Bitstream Vera Sans Mono, Courier New, monospace;

  @media (prefers-color-scheme: dark) {
    background: #111;
  }
`
const Grid = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  flex-wrap: wrap;
  max-width: 800px;

 @media (max-width: 600px) {
    width: 100%;
    flex-direction: column;
  }
`
const Card = styled.a`
  margin: 1rem;
  padding: 1.5rem;
  text-align: left;
  color: inherit;
  text-decoration: none;
  border: 1px solid #eaeaea;
  border-radius: 10px;
  transition: color 0.15s ease, border-color 0.15s ease;
  max-width: 360px;

  &:hover, :focus, :active {
      color: #0070f3;
      border-color: #0070f3;
    }

  @media (prefers-color-scheme: dark) {
    border-color: #222;
  }
  
`
const CardTitle = styled.h2`
  margin: 0 0 1rem 0;
  font-size: 1.5rem;
  font-weight: 500;
`
const CardDescription = styled.p`
  margin: 0;
  font-size: 18px;
  line-height: 1.555555556;
  font-weight: 300;
  letter-spacing: 0.2px;
  color: #425466;
`
const Logo = styled.span`
  height: 1em;
  margin-left: 0.5rem;

  & img {
    @media (prefers-color-scheme: dark) {
      filter: invert(1);
    }
  }
`
const Footer = styled.footer`
  display: flex;
  flex: 1;
  padding: 2rem 0;
  border-top: 1px solid #eaeaea;
  justify-content: center;
  align-items: center;

  & a {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-grow: 1;
  }

  @media (prefers-color-scheme: dark) {
    border-color: #222;
  }
`